portal/src/routes.py
import os
import random
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from datetime import UTC, datetime
from http import HTTPStatus
from urllib.parse import urlsplit

import requests
import sqlalchemy as sa
from flask import (
    Blueprint,
    current_app,
    flash,
    jsonify,
    make_response,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user, login_required, login_user, logout_user
from opentelemetry import trace

from src.cluster import (
    APP_NAME,
    ARCADE_HOST,
    player_cloud_job_complete,
    player_cloud_job_create,
    player_deployment_create,
    player_deployment_ready,
)
from src.db import db
from src.forms import (
    LoginForm,
    RegistrationForm,
)
from src.models import User
from src.questions import _handle_splunk_webhook_content, _handle_splunk_webhook_content_openai

routes = Blueprint("routes", __name__)


SPLUNK_OBSERVABILITY_REALM = os.getenv("SPLUNK_OBSERVABILITY_REALM", "")
SPLUNK_OBSERVABILITY_API_ACCESS_TOKEN = os.getenv("SPLUNK_OBSERVABILITY_API_ACCESS_TOKEN", "")


WAIT_ARCADE_CHOICES = [
    "Initializing Terraform to provision your custom dashboards...",
    "Deploying your player's environment in the Kubernetes cluster...",
    "Compiling amphibious movement heuristics... 🐸",
    "Calibrating quantum log stability...",
    "Defending against rogue Space Invaders... 🚀",
    "Recalibrating Duck Hunt hitboxes... the dog is still laughing. 🎯🐶",
]


@routes.before_request
def before_request():
    if current_user.is_authenticated:
        found_user = db.first_or_404(sa.select(User).where(User.username == current_user.username))
        current_user.last_seen = datetime.now(UTC)
        db.session.commit()
        session["username"] = found_user.username
        session["user_id"] = found_user.id
        session["first_name"] = found_user.first_name
        session["last_name"] = found_user.last_name
        session["email"] = found_user.email


@routes.route("/alive", methods=["GET"])
def alive():
    return jsonify(success=True)


@routes.app_errorhandler(404)
def page_not_found_handler(e):
    _ = e

    # redirect anything that would 404 to index
    return redirect(url_for("routes.index"))


@routes.app_errorhandler(Exception)
def exception_handler(e):
    # crash for any non 404 exception, we want to let k8s deal w/ crash loop
    print(f"unhandled exception {e}, crashing... bye")
    os._exit(1)


@routes.route("/")
@login_required
def index():
    if not current_user.is_authenticated:
        return redirect(url_for("routes.login"))

    return redirect(url_for("routes.wait_arcade", login=True))


@routes.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("routes.wait_arcade", login=True))

    form = LoginForm()

    if form.validate_on_submit():
        if form.username.data == "devplayer":
            devplayer_user = db.session.scalar(sa.select(User).where(User.username == "devplayer"))

            if devplayer_user is not None:
                login_user(devplayer_user, remember=False)
                return redirect(url_for("routes.wait_arcade", login=True))

            # ensure devplayer user exists
            devplayer_user = User(
                username="devplayer",
                email="devplayer@splunk.com",
                uuid=uuid.uuid4(),
                first_name="dev",
                last_name="player",
            )
            devplayer_user.set_password("password")
            db.session.add(devplayer_user)
            db.session.commit()

            login_user(devplayer_user, remember=False)
            return redirect(url_for("routes.wait_arcade", login=True))

        user = db.session.scalar(sa.select(User).where(User.username == form.username.data))

        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")

            return redirect(url_for("routes.login"))

        login_user(user, remember=form.remember_me.data)

        next_page = url_for("routes.login")

        if not next_page or urlsplit(next_page).netloc != "":
            next_page = url_for("routes.wait_arcade", login=True)

        return redirect(next_page)

    return render_template("auth-login.html", title="Log In", form=form)


@routes.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("routes.login"))


def _register(player_id: str):
    if SPLUNK_OBSERVABILITY_API_ACCESS_TOKEN != "REPLACE_ME":
        player_cloud_job_completed = player_cloud_job_complete(
            player_id=player_id,
        )
        print(
            f"player {player_id} cloud job (tf chart creation) state: {player_cloud_job_completed}"
        )

    player_deployment_create(
        player_id=player_id,
        observability_realm=SPLUNK_OBSERVABILITY_REALM,
    )
    print(f"player {player_id} cabinet deployment complete")


@routes.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("routes.index"))

    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            uuid=uuid.uuid4(),
            first_name=form.first_name.data,
            last_name=form.last_name.data,
        )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()

        # create the player's job (that creates its charts in o11y cloud) and their deployment
        if SPLUNK_OBSERVABILITY_API_ACCESS_TOKEN == "REPLACE_ME":
            print("observability api token unset, skipping cloud job create...")
        else:
            player_cloud_job_create(
                player_id=form.username.data,
                observability_token=SPLUNK_OBSERVABILITY_API_ACCESS_TOKEN,
                observability_realm=SPLUNK_OBSERVABILITY_REALM,
            )

            print(
                f"player {form.username.data} cloud job created, "
                "spawning background thread to wait and create cabinet deployment..."
            )

        executor = ThreadPoolExecutor(max_workers=1)
        executor.submit(_register, form.username.data)

        return redirect(url_for("routes.login"))

    return render_template("auth-register.html", title="Register", form=form)


@routes.route("/wait-arcade", methods=["GET"])
def wait_arcade():
    if not current_user.is_authenticated:
        return redirect(url_for("routes.login"))

    if player_deployment_ready(player_id=session["username"]):
        resp = make_response(
            redirect(f"http://{ARCADE_HOST}/player/{session["username"]}", code=302),
        )

        time.sleep(1)

        return resp

    return render_template(
        "wait-arcade.html",
        title="Waiting",
        user=session,
        message=random.choice(WAIT_ARCADE_CHOICES),
    )


def calculate_quiz_answer_score(
    attempts: int,
    time_taken: float,
) -> float:
    attempt_score = {1: 1.0, 2: 0.75, 3: 0.5, 4: 0.25}.get(attempts, 0)

    time_score = max(0, min(1, 1 - (time_taken / 3600)))

    total_score = (attempt_score + time_score) / 2

    return round(total_score * 100)


def calculate_blended_score(
    game_score: int,
    quiz_score: int,
    max_game_score: int,
):
    game_weight = 0.6
    quiz_weight = 0.4

    normalized_game_score = game_score / max_game_score if max_game_score > 0 else 0

    overall_score = (normalized_game_score * game_weight) + (quiz_score * quiz_weight)

    return round(overall_score)


@routes.route("/scoreboard")
@login_required
def scoreboard():  # noqa C901
    if not current_user.is_authenticated:
        return redirect(url_for("routes.login"))

    game_scores = requests.get(f"http://{APP_NAME}-scoreboard/get_game_scores")

    _high_scores_per_game_session = {}
    for game_score in game_scores.json():
        if game_score["game_session_id"] not in _high_scores_per_game_session:
            _high_scores_per_game_session[game_score["game_session_id"]] = {
                "title": game_score["title"],
                "version": game_score["version"],
                "player_name": game_score["player_name"],
                "current_score": int(game_score["current_score"]),
            }
            continue

        if (
            game_score["current_score"]
            > _high_scores_per_game_session[game_score["game_session_id"]]["current_score"]
        ):
            _high_scores_per_game_session[game_score["game_session_id"]]["current_score"] = int(
                game_score["current_score"]
            )

    _high_scores_cumulative = {}
    for game_score in game_scores.json():
        if game_score["player_name"] not in _high_scores_cumulative:
            _high_scores_cumulative[game_score["player_name"]] = {
                "title": game_score["title"],
                "player_name": game_score["player_name"],
                "current_score": int(game_score["current_score"]),
            }
            continue

        _high_scores_cumulative[game_score["player_name"]]["current_score"] += int(
            game_score["current_score"]
        )

    quiz_scores = requests.get(f"http://{APP_NAME}-scoreboard/get_quiz_scores")

    _high_scores_quiz = {}
    for quiz_score in quiz_scores.json():
        if quiz_score["player_name"] not in _high_scores_quiz:
            _high_scores_quiz[quiz_score["player_name"]] = {
                "player_name": quiz_score["player_name"],
                "current_score": calculate_quiz_answer_score(
                    attempts=int(quiz_score["attempts"]), time_taken=float(quiz_score["time_taken"])
                ),
            }
            continue

        _high_scores_quiz[quiz_score["player_name"]]["current_score"] += (
            calculate_quiz_answer_score(

portal/src/templates/auth-login-2.html
<!DOCTYPE html>
<html lang="en" data-topbar-color="brand">
    <head>
        <meta charset="utf-8" />
        <title>Log In 2 | Minton - Admin & Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="{{ url_for('static',filename='assets/images/favicon.ico')}}">

		<!-- App css -->
		<link href="{{  url_for('static',filename='assets/css/bootstrap.min.css' ) }}" rel="stylesheet" type="text/css" />
		<link href="{{url_for('static',filename='assets/css/app.min.css')}}" rel="stylesheet" type="text/css" id="app-stylesheet" />

		<!-- icons -->
		<link href="{{ url_for('static',filename='assets/css/icons.min.css')}}" rel="stylesheet" type="text/css" />

		<!-- Theme Config Js -->
		<script src="{{ url_for('static',filename='assets/js/config.js')}}"></script>


    </head>

    <body class=auth-fluid-pages pb-0">

        <div class="auth-fluid">
            <!-- Auth fluid right content -->
            <div class="auth-fluid-right">
                <div class="auth-user-testimonial">
                    <h3 class="mb-3 text-white">Very elegant & impressive!</h3>
                    <p class="lead fw-normal"><i class="mdi mdi-format-quote-open"></i> I've been using this theme for a while and I must say that whenever I am looking for a design - I refer to this theme for specifics & implementation. With wide arrays of components, designs, charts - I would highly recommend this theme for anyone using it for dashboard or project management usage.. <i class="mdi mdi-format-quote-close"></i>
                    </p>
                    <h5 class="text-white">
                        - Admin User
                    </h5>
                </div> <!-- end auth-user-testimonial-->
            </div>
            <!-- end Auth fluid right content -->

            <!--Auth fluid left content -->
            <div class="auth-fluid-form-box">
                <div class="align-items-center d-flex h-100">
                    <div class="card-body">

                        <!-- Logo -->
                        <div class="auth-brand text-center text-lg-start">
                            <div class="auth-logo">
                                <a href="index.html.old" class="logo logo-dark text-center">
                                    <span class="logo-lg">
                                        <img src="{{ url_for('static',filename='assets/images/logo-dark.png')}}" alt="" height="22">
                                    </span>
                                </a>
            
                                <a href="index.html.old" class="logo logo-light text-center">
                                    <span class="logo-lg">
                                        <img src="{{ url_for('static',filename='assets/images/Splunk-Corp-Logo-K-rgb.png')}}" alt="" height="100">
                                        <img src="{{ url_for('static',filename='assets/images/logo-light.png')}}" alt="" height="100">

                                    </span>
                                </a>
                            </div>
                        </div>

                        <!-- title-->
                        <h4 class="mt-0">Sign In</h4>
                        <p class="text-muted mb-4">Enter your email address and password to access admin panel.</p>

                        <!-- form -->
                        <form action="" method="post">
                            {{ form.hidden_tag() }}
                            <div class="mb-2">
                                {{ form.username.label }}<br>
                                {{ form.username(size=32, class_="form-control") }}
                                  {% for error in form.username.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                    {% endfor %}


                            </div>
                            <div class="mb-2">
                                <a href="auth-recoverpw-2.html" class="text-muted float-end"><small>Forgot your password?</small></a>
                                {{ form.password.label }}
                                <div class="input-group input-group-merge">
                                    <br>
                                {{ form.password(size=32, class_="form-control") }}<br>
                                    {% for error in form.password.errors %}
                                        <span style="color: red;">[{{ error }}]</span>
                                    {% endfor %}


                                    <div class="input-group-text" data-password="false">
                                        <span class="password-eye"></span>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="mb-3">
                                <div class="form-check">
                                     {{ form.remember_me() }}
                                    <label class="form-check-label" for="checkbox-signin">
                                       {{ form.remember_me.label }}
                                    </label>
                                </div>
                            </div>
                            <div class="d-grid text-center">
                                {{ form.submit() }}
                            </div>

                        </form>
                        <!-- end form-->

                        <!-- Footer-->
                        <footer class="footer footer-alt">
                            <p class="text-muted">Don't have an account? <a href="{{ url_for('routes.register') }}" class="text-primary fw-medium ms-1">Sign Up</a></p>
                        </footer>

                    </div> <!-- end .card-body -->
                </div> <!-- end .align-items-center.d-flex.h-100-->
            </div>
            <!-- end auth-fluid-form-box-->
        </div>
        <!-- end auth-fluid-->

        <!-- Vendor js -->
        <script src="{{ url_for('static',filename='assets/js/vendor.min.js')}}"></script>

        <!-- App js -->
        <script src="{{ url_for('static',filename='assets/js/app.min.js')}}"></script>
        
    </body>
</html>

portal/src/templates/auth-login.html
<!DOCTYPE html>
<html lang="en" data-topbar-color="brand">
    <head>
        <meta charset="utf-8"/>
        <title>Login to the Splunk Arcade!</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

        <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico')}}">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/output.css')}}">
    </head>

    <body>
        <section class="h-screen bg-gray-900 flex">
            <div
                    class="w-1/2 h-full bg-cover bg-center"
                    style="background-image: url('{{ url_for('static', filename='images/giphy.webp') }}');">
            </div>

            <div class="w-1/2 h-full flex flex-col items-center justify-center bg-gray-800 relative">
                <form action="" method="post" class="bg-gray-700 p-8 rounded-lg shadow-lg w-full max-w-md">
                    <div class="mb-6 text-center">
                        <img
                                src="{{ url_for('static', filename='images/splunk_logo.png') }}"
                                alt="Logo"
                                class="w-48 mx-auto"
                        >
                    </div>

                    {{ form.hidden_tag() }}

                    <div class="mb-4">
                        <label for="username" class="text-gray-300">
                            {{ form.username.label }}
                        </label>
                        <input
                                type="text"
                                name="username"
                                id="username"
                                class="form-control bg-gray-600 text-gray-100 rounded-md p-2 w-full mt-1
                       focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                value=""
                        >
                        {% for error in form.username.errors %}
                        <span class="text-red-500 text-sm">
                [{{ error }}]
            </span>
                        {% endfor %}
                    </div>

                    <div class="mb-4">
                        <label for="password" class="text-gray-300">
                            {{ form.password.label }}
                        </label>
                        <input
                                type="password"
                                name="password"
                                id="password"
                                class="form-control bg-gray-600 text-gray-100 rounded-md p-2 w-full mt-1
                       focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                value=""
                        >
                        {% for error in form.password.errors %}
                        <span class="text-red-500 text-sm">
                [{{ error }}]
            </span>
                        {% endfor %}
                    </div>

                    <div class="d-grid text-center mt-4">
                        <button
                                type="submit"
                                class="bg-pink-500 text-white py-2 px-4 rounded-lg w-full hover:bg-pink-600
                       focus:outline-none focus:ring-2 focus:ring-pink-500"
                        >
                            Sign In
                        </button>
                    </div>

                    <div class="text-center mt-4">
                        <a
                                href="{{ url_for('routes.register') }}"
                                class="text-purple-400 hover:text-purple-500"
                        >
                            Don't have an account? Register here
                        </a>
                    </div>
                </form>

                <div class="mt-8 text-gray-500 text-center">
                    Made with ❤️ by
                    <a
                            href="https://www.splunk.com"
                            target="_blank"
                            class="text-pink-400 hover:text-purple-500"
                    >
                        Splunk
                    </a>
                </div>
            </div>
        </section>
    </body>
</html>

portal/src/templates/auth-register.html
<!DOCTYPE html>
<html lang="en" data-topbar-color="brand">
    <head>
        <meta charset="utf-8"/>
        <title>Login to the Splunk Arcade!</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

        <link rel="shortcut icon" href="{{ url_for('static',filename='images/favicon.ico')}}">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/output.css')}}">
    </head>

    <body>
        <section class="h-screen bg-gray-900 flex">
            <div class="w-1/2 h-full flex flex-col items-center justify-center bg-gray-800 relative">
                <form
                        action=""
                        method="post"
                        class="bg-gray-700 p-8 rounded-lg shadow-lg w-full max-w-md"
                >
                    {{ form.hidden_tag() }}

                    <div class="mb-4">
                        <label for="first_name" class="text-gray-300">
                            {{ form.first_name.label }}
                        </label>
                        {{ form.first_name(size=32, class_="form-control bg-gray-600 text-gray-100 rounded-md p-2 w-full mt-1 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent") }}
                    </div>

                    <div class="mb-4">
                        <label for="last_name" class="text-gray-300">
                            {{ form.last_name.label }}
                        </label>
                        {{ form.last_name(size=32, class_="form-control bg-gray-600 text-gray-100 rounded-md p-2 w-full mt-1 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent") }}
                    </div>

                    <div class="mb-4">
                        <label for="username" class="text-gray-300">
                            {{ form.username.label }}
                        </label>
                        {{ form.username(size=32, class_="form-control bg-gray-600 text-gray-100 rounded-md p-2 w-full mt-1 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent") }}
                        {% for error in form.username.errors %}
                        <span class="text-red-500 text-sm">[{{ error }}]</span>
                        {% endfor %}
                    </div>

                    <div class="mb-4">
                        <label for="email" class="text-gray-300">
                            {{ form.email.label }}
                        </label>
                        {{ form.email(size=32, class_="form-control bg-gray-600 text-gray-100 rounded-md p-2 w-full mt-1 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent") }}
                        {% for error in form.email.errors %}
                        <span class="text-red-500 text-sm">[{{ error }}]</span>
                        {% endfor %}
                    </div>

                    <div class="mb-4">
                        <label for="password" class="text-gray-300">
                            {{ form.password.label }}
                        </label>
                        <div class="relative">
                            {{ form.password(size=32, class_="form-control bg-gray-600 text-gray-100 rounded-md p-2 w-full mt-1 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent") }}
                            <div class="absolute inset-y-0 right-0 flex items-center pr-3 cursor-pointer">
                                <span class="password-eye"></span>
                            </div>
                        </div>
                        {% for error in form.password.errors %}
                        <span class="text-red-500 text-sm">[{{ error }}]</span>
                        {% endfor %}
                    </div>

                    <div class="mb-4">
                        <label for="password2" class="text-gray-300">
                            {{ form.password2.label }}
                        </label>
                        <div class="relative">
                            {{ form.password2(size=32, class_="form-control bg-gray-600 text-gray-100 rounded-md p-2 w-full mt-1 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent") }}
                            <div class="absolute inset-y-0 right-0 flex items-center pr-3 cursor-pointer">
                                <span class="password-eye"></span>
                            </div>
                        </div>
                        {% for error in form.password2.errors %}
                        <span class="text-red-500 text-sm">[{{ error }}]</span>
                        {% endfor %}
                    </div>

                    <div class="flex justify-center">
                        <div class="mb-4">
                            <div class="flex items-center">
                                {{ form.accept_tos(class="form-check-input bg-gray-600 border-gray-500 text-blue-500 focus:ring-blue-500 mt-1 mr-2") }}
                                <div>
                                    <label class="text-gray-300">
                                        {{ form.accept_tos.label }}
                                    </label>
                                </div>
                            </div>
                            {% for error in form.accept_tos.errors %}
                            <span class="text-red-500 text-sm">[{{ error }}]</span>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="text-center mt-4">
                        <a
                                href="{{ url_for('routes.login') }}"
                                class="text-purple-400 hover:text-purple-500"
                        >
                            Already have an account? Login here
                        </a>
                    </div>

                    <div class="d-grid text-center mt-6">
                        <button
                                type="submit"
                                class="bg-pink-500 text-white py-2 px-4 rounded-lg w-full hover:bg-pink-600 focus:outline-none focus:ring-2 focus:ring-pink-500"
                        >
                            Sign Up
                        </button>
                    </div>
                </form>

                <div class="mt-8 text-gray-500 text-center">
                    Made with ❤️ by
                    <a
                            href="https://www.splunk.com"
                            target="_blank"
                            class="text-pink-400 hover:text-purple-500"
                    >
                        Splunk
                    </a>
                </div>
            </div>
            <div
                    class="w-1/2 h-full bg-cover bg-center"
                    style="background-image: url('{{ url_for('static', filename='images/giphy.webp') }}');">
            </div>
        </section>
    </body>

</html>

portal/src/templates/wait-arcade.html
<!DOCTYPE html>
<html lang="en" data-topbar-color="brand">
    <head>
        <meta charset="utf-8" />
        <title>Waiting for the fun to start...</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta http-equiv="Refresh" content="3">

        <link rel="shortcut icon" href="{{ url_for('static',filename='images/favicon.ico')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/output.css')}}">
    </head>

    <body>
    <section class="h-screen bg-gray-900 flex">
        <div
                class="w-1/2 h-full bg-cover bg-center"
                style="background-image: url('{{ url_for('static', filename='images/arcade_bg.png') }}');">
        </div>

        <div class="w-1/2 h-full flex flex-col items-center justify-center bg-gray-800 relative">

            <div class="flex flex-col items-center justify-center space-y-4">
                <p class="text-gray-300 text-xl">Waiting for your arcade to be deployed...</p>
                <p class="text-gray-300 text-lg">This may take a minute or two, sit tight!</p>
                <p class="text-gray-300 text-lg">{{ message }}</p>
                <div class="w-8 h-8 border-4 border-pink-500 border-t-transparent rounded-full animate-spin"></div>
            </div>

            <br>
            <br>
            <br>
            <br>

            <div class="mt-8 text-gray-500 text-center">
                Made with ❤️ by
                <a
                        href="https://www.splunk.com"
                        target="_blank"
                        class="text-pink-400 hover:text-purple-500"
                >
                    Splunk
                </a>
            </div>
        </div>
    </section>
    </body>
</html>