cabinet/src/routes.py
import logging
import os
import random
import uuid

import requests
from flask import Blueprint, jsonify, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from opentelemetry import trace

from src.db import db
from src.login import login
from src.models import User

routes = Blueprint("routes", __name__)


PLAYER_NAME = os.getenv("PLAYER_NAME")
ARCADE_HOST = os.getenv("ARCADE_HOST")
SCOREBOARD_HOST = os.getenv("SCOREBOARD_HOST")
PLAYER_CONTENT_HOST = os.getenv("PLAYER_CONTENT_HOST")
SPLUNK_OBSERVABILITY_REALM = os.getenv("SPLUNK_OBSERVABILITY_REALM", "us1")

IMVADERS_SLOW_VERSION = 0.75
UNPROCESSABLE_ENTITY = 422


def _realmify_dashboard_url(url: str) -> str:
    return url.replace("app.signalfx.com", f"app.{SPLUNK_OBSERVABILITY_REALM}.signalfx.com")

FINAL_DASHBOARD_URL = _realmify_dashboard_url(
    os.getenv("dashboard_url", "https://app.signalfx.com/#/dashboard/"),
)


logging.basicConfig(level=logging.INFO)
LOGGER = logging.getLogger(f"player_cabinet_{PLAYER_NAME}")


@login.user_loader
def load_user(id):
    return db.session.get(User, int(id))


@routes.route("/alive", methods=["GET"])
def alive():
    return jsonify(success=True)


@routes.app_errorhandler(404)
def page_not_found(e):
    _ = e

    # redirect anything that would 404 to index
    return redirect(url_for("routes.index"))


@routes.route("/")
@login_required
def index():
    if current_user.is_authenticated:
        return redirect(url_for("routes.home", login=True))
    else:
        return redirect(url_for("routes.login"))


@routes.route("/login")
def login():
    return redirect(f"http://{ARCADE_HOST}/login", code=302)


@routes.route("/logout")
def logout():
    return redirect(f"http://{ARCADE_HOST}/logout", code=302)


@routes.route("/home", methods=["GET", "POST"])
@login_required
def home():
    if not current_user.is_authenticated:
        return redirect(url_for("routes.login"))

    return render_template(
        "home.html",
        scoreboard_endpoint=f"http://{ARCADE_HOST}/scoreboard",
        logout_endpoint=f"http://{ARCADE_HOST}/logout",
        dashboard_home_endpoint=FINAL_DASHBOARD_URL,
    )


@routes.route("/game", methods=["GET", "POST"])
@login_required
def game():
    if not current_user.is_authenticated:
        return redirect(url_for("routes.login"))

    return render_template(
        "game.html",
        playgame=True,
        gamelist=True,
        data={
            "title": request.form.get("title"),
            "description": request.form["description"],
            "uri": request.form.get("uri"),
        },
        user_username=current_user.username,
        user_uuid=current_user.uuid,
        gamesession=uuid.uuid4(),
        scoreboard_endpoint=f"http://{ARCADE_HOST}/scoreboard",
        logout_endpoint=f"http://{ARCADE_HOST}/logout",
        dashboard_home_endpoint=FINAL_DASHBOARD_URL,
    )


@routes.route("/record_game_score/", methods=["POST"])
def record_game_score():
    content = request.get_json(force=True)

    current_span = trace.get_current_span()
    for k, v in content.items():
        current_span.set_attribute(k, v)

    # if imvaders is on "slow" version (<1), trigger some failed http reqs
    if content["title"] == "imvaders" and content["version"] == IMVADERS_SLOW_VERSION:
        try:
            ret = requests.post(
                f"http://{SCOREBOARD_HOST}/blackhole_sun",
                json=content,
            )
            print(ret.status_code, ret.text)
        except Exception as exc:
            _ = exc
            pass

        # we dont record score for slow version! gotta answer questions to get your score
        # recorded!!
        return {}

    ret = requests.post(
        f"http://{SCOREBOARD_HOST}/record_game_score/",
        json=content,
    )

    print(f"record game score status {ret.status_code}")

    return {}


@routes.route("/question/<string:module>", methods=["GET"])
def get_question(module: str):
    content = requests.get(
        f"http://{PLAYER_CONTENT_HOST}/quiz/question/{module}",
        headers={
            "Player-Name": PLAYER_NAME,
        },
    )

    question_content = content.json()

    if question_content.get("link_text") and not question_content.get("link"):
        # for questions that provide link text but not a specific link we
        # insert the link we built from tf data + realm info
        question_content["link"] = FINAL_DASHBOARD_URL

    return jsonify(question_content)


@routes.route("/answer", methods=["POST"])
def record_answer():
    content = request.get_json(force=True)

    ret = requests.post(
        f"http://{SCOREBOARD_HOST}/record_quiz_score/",
        json=content,
    )

    print(f"record quiz score status {ret.status_code}")

    return {}


@routes.route("/record_question_thumbs_up_down", methods=["POST"])
def record_question_thumbs_up_down():
    # we'll have the js just send {"question": "the question prompt as this is unique enough to id"}
    content = request.get_json(force=True)

    ret = requests.post(
        f"http://{SCOREBOARD_HOST}/record_question_thumbs_up_down",
        headers={
            "Player-Name": PLAYER_NAME,
        },
        json=content,
    )

    print(f"record question thumps up/down status {ret.status_code}")

    return {}


@routes.route("/reset_quiz_scores", methods=["POST"])
def reset_quiz_scores():
    ret = requests.post(
        f"http://{SCOREBOARD_HOST}/reset_player_quiz_scores",
        headers={
            "Player-Name": PLAYER_NAME,
        },
    )

    print(f"reset quiz score status {ret.status_code}")

    return {}


@routes.route("/walkthrough/<string:module>/<string:stage>", methods=["GET"])
def get_walkthrough(module: str, stage: str):
    content = requests.get(f"http://{PLAYER_CONTENT_HOST}/walkthrough/{module}/{stage}")

    if content.status_code == UNPROCESSABLE_ENTITY:
        # signal to the front end that they ran out of content
        return {}

    return content.json()


@routes.route("/progression", methods=["GET"])
def get_progression():
    ret = requests.get(
        f"http://{SCOREBOARD_HOST}/player_progression",
        headers={
            "Player-Name": PLAYER_NAME,
        },
    )

    return ret.json()


@routes.route("/imvaders_version", methods=["GET"])
def get_imvaders_version():
    ret = requests.get(
        f"http://{SCOREBOARD_HOST}/player_progression",
        headers={
            "Player-Name": PLAYER_NAME,
        },
    )

    return {"version": ret.json()["game_versions"].get("imvaders") or 0.75}


@routes.route("/get_logger_shrink_state", methods=["GET"])
def get_logger_shrink_state():
    ret = requests.get(
        f"http://{SCOREBOARD_HOST}/player_progression",
        headers={
            "Player-Name": PLAYER_NAME,
        },
    )

    return {"version": ret.json()["game_versions"].get("logger") or 1.29}


@routes.route("/are_you_not_entertained", methods=["GET", "POST"])
def are_you_not_entertained():
    return render_template("doom.html")


def _logger_log(content: str):
    log_messages = [LOGGER.info, content]

    if "shrinkify" in content:
        log_messages = [
            (LOGGER.warning, "Quantum Log Shrinkage Uncertainty: It exists… but also doesn't."),
            (LOGGER.warning, "Log Shrinkage Detected: Hope you've been practicing your jumps!"),
            (LOGGER.warning, "Structural Integrity Failing: This log shrinking to 50% nostalgia."),
            (LOGGER.warning, "Log Density Shrinkage: Someone forgot to pay the tree rent."),
            (LOGGER.warning, "Log Vaporization Imminent: No logs left to shrink."),
        ]
    elif "you killed a frog" in content:
        log_messages = [
            (
                LOGGER.critical,
                "Amphibian Anomaly: You exist in a quantum state of both 'ribbit' and 'rib-GONE'.",
            ),
            (
                LOGGER.critical,
                "Toad Traffic Violation: Failure to yield to a semi-truck. Penalty: one life.",
            ),
            (LOGGER.error, "Frog Detour Failed: Turns out the river was just hungry today."),
            (LOGGER.error, "Respawn Tax Implemented: The afterlife is getting expensive."),
            (LOGGER.critical, "Frogger Fatality: Your insurance doesn't cover reckless hopping."),
            (LOGGER.critical, "Hopper Down: The universe just subtracted you."),
        ]
    elif "hop hop hop" in content:
        log_messages = [
            (
                LOGGER.info,
                "Frog Fact: A single leap can change your whole trajectory—both in"
                " life and on the highway.",
            ),
            (LOGGER.info, "Pond Update: Water is still wet. Log availability fluctuating."),
            (
                LOGGER.info,
                "Bug Buffet Alert: All-you-can-eat fly special available on lily pad #3.",
            ),
            (
                LOGGER.info,
                "Traffic Advisory: Vehicles show no sign of slowing. Hopping recommended.",
            ),
            (
                LOGGER.info,
                "Amphibian Analytics: Hopping efficiency up 12%, but reckless road crossings"
                " remain a concern.",
            ),
            (LOGGER.info, "River Status: Logs are floating, turtles are plotting."),
            (
                LOGGER.info,
                "Frog Philosophy: Sometimes the safest path is also the most boring. Hop wisely.",
            ),
            (LOGGER.info, "Footwear Forecast: Zero frog-friendly crosswalks detected."),
            (LOGGER.info, "Bug Economics: Supply remains steady, demand remains infinite."),
            (LOGGER.info, "Frogger Metrics: Total leaps today: 37. Successful crossings: TBD."),
        ]

    return random.choice(log_messages)


@routes.route("/log", methods=["POST"])
def log():
    content = request.get_json(force=True)

    current_span = trace.get_current_span()
    for k, v in content.items():

cabinet/src/templates/doom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
    <meta name="description" content="Play DOOM via JS-DOS.">
    <meta name="keywords" content="DOOM,pc,game,javscript">
    <title>Play DOOM via JS-DOS</title>
    <meta property="og:title" content='DOOM &middot; js-dos' />
    <meta property="og:description" content="Play in the DOOM in browser." />
    <meta property="og:type" content="game" />

    <link rel="stylesheet" href="{{ url_for('static', filename='doom/app.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700|Abril+Fatface">

    <link rel="icon" type="image/png" href="{{ url_for('static', filename='doom/favicon.ico')}}">
    <link rel="manifest" href="{{ url_for('static', filename='doom/site.webmanifest')}}">

    <script type="text/javascript" src="https://thedoggybrad.github.io/doom_on_js-dos/js-dos-api.js" src="{{ url_for('static', filename='doom/js-dos-api.js')}}"></script>

<body style="background-color:#121212; color: white">
<style>
    #DOOM > .dosbox-container { width: 800px; height: 500px; }
    #DOOM > .dosbox-container > .dosbox-overlay { background: url('{{ url_for('static', filename='doom/DOOM.png') }}'); }
    #DOOM > .dosbox-container > .dosbox-overlay > .dosbox-start {
        border-radius: 17px 17px 17px 17px;
        -moz-border-radius: 17px 17px 17px 17px;
        -webkit-border-radius: 17px 17px 17px 17px;
        border: 0px solid #000000;
        background-color: rgba(90, 90, 90, 0.57);
        padding: 5px;
        text-align: center;
        vertical-align: middle;
        width: 10em;
        margin: 0 auto;
    }
    a:link {color:white}
</style>
<center>
    <h1>Play DOOM via JS-DOS</h1>
    <footer>©TheDoggyBrad Software Lab. All Rights Reserved.</footer>
    <h3><a href="https://github.com/thedoggybrad/doom_on_js-dos/blob/main/MANUAL.MD">User Manual</a></h3>
    <div style="margin-top:20px;" id="DOOM" class="dosbox-default"></div>
    <p><br /><a id="fullscreen_DOOM" href="javascript: void 0;" class="fa-solid fa-expand"></a>&nbsp;&nbsp;FULLSCREEN</p>

    <script type="text/javascript">
        var dosbox_DOOM = new Dosbox({
            id: "DOOM",
            onload: function (dosbox) {
                dosbox_DOOM.run("{{ url_for('static', filename='doom/DOOM-@evilution.zip') }}", "./DOOM/DOOM.EXE");
            },
            onrun: function (dosbox, app) {
                console.log("App '" + app + "' is ran");
            }
        });

        document.getElementById("fullscreen_DOOM").addEventListener("click", function() {
            dosbox_DOOM.requestFullScreen();
        });
    </script>
</center>
</body>
</html>

cabinet/src/templates/footer.html
<footer class="mt-auto bg-gray-800 opacity-90 text-white p-4 text-center flex items-center relative">
    <p class="flex-grow text-center">
        Made with ❤️ by <a href="https://www.splunk.com" target="_blank" class="text-blue-400 hover:text-blue-500">Splunk</a>
    </p>

    <button id="resetButton" class="absolute right-4 bottom-4 bg-red-500 text-white px-2 py-1 text-sm rounded hover:bg-red-600">
        Reset Quiz Data
    </button>

    <button id="boredButton" class="absolute left-4 bottom-4 bg-pink-600 text-white px-2 py-1 text-sm rounded hover:bg-purple-600 cursor-not-allowed opacity-50" disabled
            onclick="window.location.href='{{ url_for('routes.are_you_not_entertained') }}'">
        Bored?
    </button>
</footer>

<div id="popupDialog" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center hidden">
    <div class="bg-white p-6 rounded-lg shadow-lg max-w-sm w-full">
        <h2 class="text-lg font-semibold mb-4">Are you sure?</h2>
        <p class="mb-4">This action will reset your quiz data.</p>
        <div class="flex justify-end">
            <button id="cancelButton" class="bg-gray-300 text-gray-800 px-4 py-2 rounded mr-2 hover:bg-gray-400">Cancel</button>
            <button id="confirmButton" class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600">Confirm</button>
        </div>
    </div>
</div>

<script>
    const resetButton = document.getElementById('resetButton');
    const popupDialog = document.getElementById('popupDialog');
    const cancelButton = document.getElementById('cancelButton');
    const confirmButton = document.getElementById('confirmButton');

    resetButton.addEventListener('click', () => {
        popupDialog.classList.remove('hidden');
    });

    cancelButton.addEventListener('click', () => {
        popupDialog.classList.add('hidden');
    });

    confirmButton.addEventListener('click', () => {
        $.ajax({
            type: 'POST',
            url: '{{ url_for("routes.reset_quiz_scores") }}',
            success: function(_) {
                alert("Quiz score data has been reset!");
                location.reload(); // force page reload to re-render the locked banners etc
            },
            error: function(error) {
                console.log(error);
            }
        });
        popupDialog.classList.add('hidden');
        checkGameStatus();
    });
</script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const scoreboardEndpoint = "{{ scoreboard_endpoint }}";
        const referrer = encodeURIComponent(window.location.href);

        document.getElementById("scoreboardLink").href = `${scoreboardEndpoint}?referrer=${referrer}`;
    });
</script>

cabinet/src/templates/head_content.html
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico')}}">

<link rel="stylesheet" href="{{ url_for('static', filename='css/output.css')}}">

<script src="https://code.jquery.com/jquery-latest.js"></script>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap');
    .press-start-2p-regular {
        font-family: "Press Start 2P", serif;
        font-weight: 400;
        font-style: normal;
    }
</style>

<script>
    function submitForm(titleKey, descriptionKey, uriKey) {
        const form = document.getElementById('gameForm');
        const title = document.createElement('input');
        title.type = 'hidden';
        title.name = 'title';
        title.value = titleKey;

        const description = document.createElement('input');
        description.type = 'hidden';
        description.name = 'description';
        description.value = descriptionKey;

        const uri = document.createElement('input');
        uri.type = 'hidden';
        uri.name = 'uri';
        uri.value = uriKey;

        form.appendChild(title);
        form.appendChild(description);
        form.appendChild(uri);

        form.submit();
    }
</script>

<script>
    const gameTileOnClicks = {
        logger: () => submitForm('logger', 'Leap for your logs!', 'logger.html'),
        bughunt: () => submitForm('bughunt', 'Hunt some bugs!', 'bughunt.html'),
        floppybird: () => submitForm('flappybird', 'FlipFlapFlop', 'floppybird.html'),
        zelda: () => submitForm('zelda', 'Are you the Link?', 'zelda.html'),
    };

    async function checkGameStatus() {
        try {
            let response = await fetch("{{url_for('routes.get_progression')}}");
            let data = await response.json();
            data = data["level_state"];

            for (let gameId in data) {
                const storedState = localStorage.getItem(gameId);

                if (data[gameId] === "unlocked" && storedState === "locked") {
                    const event = new CustomEvent('gameStateChanged', {
                        detail: {
                            gameId: gameId,
                            oldState: "locked",
                            newState: "unlocked"
                        }
                    });
                    window.dispatchEvent(event);
                }

                localStorage.setItem(gameId, data[gameId]);
            }

            updateUIWithGameState(data);
        } catch (error) {
            console.error("Error fetching game status:", error);
        }
    }

    function updateUIWithGameState(gameState) {
        document.querySelectorAll("[data-game]").forEach(card => {
            let gameId = card.dataset.game;
            let banner = card.querySelector(".locked-banner");

            card.classList.add("relative");

            console.log("STATE > ", gameState[gameId], gameId);

            if (gameState[gameId] === "unlocked" && gameId !== "other") {
                card.classList.remove("cursor-not-allowed");

                if (banner) {
                    card.classList.remove("cursor-not-allowed");
                    card.classList.add("cursor-pointer");
                    card.removeChild(banner);
                    card.onclick = gameTileOnClicks[gameId];
                }
            }
        });

        if (gameState["doom"] === "unlocked") {
            const button = document.getElementById("boredButton");
            button.removeAttribute("disabled");
            button.classList.remove("opacity-50", "cursor-not-allowed");
        }
    }

    document.addEventListener("DOMContentLoaded", () => {
        // run once on page load then every 7s
        checkGameStatus();
        setInterval(checkGameStatus, 7000);
    });
</script>